gazebo_ros_control:
  pid_gains:
    joint_1: 
      p: [0.5, 0, 0, 0, 0, 0]
      i: [0.0001, 0, 0, 0, 0, 0]
      d: [0.1, 0, 0, 0, 0, 0]
    joint_2: 
      p: [0, 0.5, 0, 0, 0, 0]
      i: [0, 0.0001, 0, 0, 0, 0]
      d: [0, 0.1, 0, 0, 0, 0]
    joint_3: 
      p: [0, 0, 0.5, 0, 0, 0]
      i: [0, 0, 0.0001, 0, 0, 0]
      d: [0, 0, 0.1, 0, 0, 0]
    joint_4: 
      p: [0, 0, 0, 0.5, 0, 0]
      i: [0, 0, 0, 0.0001, 0, 0]
      d: [0, 0, 0, 0.5, 0, 0]
    joint_5: 
      p: [0, 0, 0, 0, 0.5, 0]
      i: [0, 0, 0, 0, 0.0001, 0]
      d: [0, 0, 0, 0, 0.5, 0]
    joint_6: 
      p: [0, 0, 0, 0, 0, 0.5]
      i: [0, 0, 0, 0, 0, 0.0001]
      d: [0, 0, 0, 0, 0, 0.5]

